### ISSUE TITLE
Is there any mistakes on the experimental results in Fig.5 in your original paper?

### ISSUE THREAD

**Issue by sqhan-Husky** [FFL2022/FFL#1]
Hello, thank you for your work on FL and for making it open-source.
I have carefully read your published paper but found weird experiment results in Fig.5.  The comparison of FFL with four baseline techniques on the 2 datasets is the same in plot 5(a) and plot 5(b). 
I guess there is something wrong with the result on Prutor.

<img width="720" alt="1670209733358" src="https://user-images.githubusercontent.com/45597101/205541088-c52504b7-4067-4053-a8a7-5ea5652a2150.png">

**Comment by datvo06** [comment]
Hi, @sqhan-Husky, thank you so much for pointing out this issue, I have updated the paper here: https://datvo06.github.io/assets/pdf/FFL_Final.pdf

**Comment by sqhan-Husky** [comment]
Thank you for your revision. @datvo06 
I think FFL is really great work to have outstanding results on the benchmarks. (*￣︶￣)
